title: MPFE Consultancy Ltd
remote_theme: hydecorp/hydejack@v9.1.2
accent_image: /assets/img/mpfe-bg.jpg
menu:
  - title: Home
    url:   /
  - title: Projects
    url:   /projects/
  - title: About
    url:   /about/
  - title: Blog
    url:   /blog/
