remote_theme: hydecorp/hydejack@v9
title: MPFE Consultancy Ltd
accent_image: /assets/img/mpfe-bg-windows.jpg
menu:
  - title: Home
    url:   /
  - title: Projects
    url:   /projects/
  - title: About
    url:   /about/
  - title: Blog
    url:   /blog/

lang: en
description:  >
  MPFE Consultancy Ltd is an IT Services company providing UK businesses
  with Microsoft-centric DevOps, Infrastructure and Cloud expertise.
# A shorter description for the sidebar.
tagline: A DevOps, Infrastructure and Cloud Services Provider for UK business

# A list of keywords for your blog
keywords: [DevOps, Microsoft, Cloud, Azure, AWS, PowerShell, Infrastructure, Windows, Server]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo: /assets/img/mpfe.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name: Mark Wragg
  email: mark@mpfe.uk

# This text will appear in a `<small>` tag in the footer of every page.
copyright: © 2021. All rights reserved.

# Format of the permalinks
permalink: /:categories/:year-:month-:day-:title/
