remote_theme: hydecorp/hydejack@v9

title: MPFE Consultancy Ltd

accent_image: /assets/img/mpfe-bg-windows.jpg
accent_color:          rgb(64,64,64)

menu:
  - title: Home
    url:   /
  - title: About
    url:   /about/
  - title: Projects
    url:   /projects/
  - title: Blog
    url:   /blog/
    
collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

lang: en
description:  >
  MPFE Consultancy Ltd is an IT Services company providing UK businesses
  with Microsoft-centric DevOps, Infrastructure and Cloud expertise.
# A shorter description for the sidebar.
tagline: A DevOps, Infrastructure and Cloud Services Provider for UK business

# A list of keywords for your blog
keywords: [DevOps, Microsoft, Cloud, Azure, AWS, PowerShell, Infrastructure, Windows, Server]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo: /assets/img/logo-cropped.jpg

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name: MPFE
  email: enquiries@mpfe.uk

copyright:             © 2021. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /:num/

